module.exports = [`

  input CreateUserInput {
    name: String
    username: String!
    avatar: String
    email: String!
    address: AddressTypeInput
  }

  input AddressTypeInput {
    street: String
    city: String
    geo: GeoLocationTypeInput
  }

  input GeoLocationTypeInput {
    lat: String
    lng: String
  }
  
`];