module.exports = [`
  type User {
    id: String!
    name: String
    username: String!
    avatar: String
    email: String!
    address: AddressType,
    posts: [ Post ],
    todos: [ Todo ]
  }

  type AddressType {
    street: String
    city: String
    geo: GeoLocationType
  }

  type GeoLocationType {
    lat: String
    lng: String
  }

  type UserList {
    total: Int
    items: [ User ]
  }
  
`];