module.exports = [`
  type Comment {
    albumId: String,
    postId: String!,
    id: String!,
    name: String,
    email: String,
    body: String!
  }

  type CommentList {
    total: Int
    items: [ Comment ]
  }
  
`];