module.exports = [`
    type Query {
        user(id: ID!): User
        users: UserList
        todo(id: ID!): Todo
        post(id: ID!): Post
        photo(id: ID!): Photo
        comment(id: ID!): Comment
    }

    type Mutation {
        createNewUser: CreateUser!
    }

    schema {
        query: Query
        mutation: Mutation
    }
`];